# coding: utf-8

"""
    AWS OAS API

    This is a simple OAS for Terraform AWS OAS project. See https://github.com/alghe-global/terraform_labs for more information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_entries_get(self) -> None:
        """Test case for entries_get

        """
        pass

    def test_entries_post(self) -> None:
        """Test case for entries_post

        """
        pass

    def test_entry_key_get(self) -> None:
        """Test case for entry_key_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
