# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_item_items_item_id_delete(self) -> None:
        """Test case for delete_item_items_item_id_delete

        Delete Item
        """
        pass

    def test_put_item_items_message_put(self) -> None:
        """Test case for put_item_items_message_put

        Put Item
        """
        pass

    def test_read_item_items_item_id_get(self) -> None:
        """Test case for read_item_items_item_id_get

        Read Item
        """
        pass

    def test_read_items_items_get(self) -> None:
        """Test case for read_items_items_get

        Read Items
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
