# coding: utf-8

# flake8: noqa
"""
    AWS OAS API

    This is a simple OAS for Terraform AWS OAS project. See https://github.com/alghe-global/terraform_labs for more information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.entry import Entry
