apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  aws_access_key_id: ${base64encode(var.AWS_EUWEST1_ACCESS_KEY)}
  aws_secret_access_key: ${base64encode(var.AWS_EUWEST1_SECRET_KEY)}
